# use to create a swarm template in Portainer
version: '3.7'

x-default-opts: 
  &default-opts
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      window: 20s
  
services:
  app:
    image: neomediatech/pdfsplit:latest
    hostname: app
    <<: *default-opts    
    ports:
      - target: 22
        published: 2223
        protocol: tcp
        mode: host
    volumes:
      - data:/data
      - /srv/data/pdfsplit/assets/pdfsplit:/usr/local/sbin/pdfsplit:ro
      - /srv/data/pdfsplit/assets/:/data/assets/:ro
  
volumes:
  data:
    driver: local
